
import React, { useState, useRef, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import { ensureApiKeySelected } from '../utils/key-selection';
import { Image as ImageIcon, Wand, Eraser, Download, Loader2, Maximize2, Sparkles, ImagePlus, Upload, Palette, Trash2, Camera, Dice5, X, Crown, Square, Monitor, Smartphone } from 'lucide-react';

type Mode = 'generate' | 'pro' | 'edit';
// Restricted to supported aspect ratios for Gemini API compatibility
type AspectRatio = '1:1' | '3:4' | '4:3' | '9:16' | '16:9';
type ProAspectRatio = '1:1' | '16:9' | '9:16';
type ImageSize = '1K' | '2K' | '4K';

export const ImageStudio: React.FC = () => {
  const [mode, setMode] = useState<Mode>('generate');
  
  // Gen State
  const [genPrompt, setGenPrompt] = useState('');
  const [genLoading, setGenLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('1:1');
  const [imageSize, setImageSize] = useState<ImageSize>('1K');
  const [genModel, setGenModel] = useState<string>('gemini-2.5-flash-image'); // Default to Flash for standard tab
  const [promptLoading, setPromptLoading] = useState(false);

  // Pro State
  const [proPrompt, setProPrompt] = useState('');
  const [proAspectRatio, setProAspectRatio] = useState<ProAspectRatio>('1:1');
  const [proLoading, setProLoading] = useState(false);
  const [proImage, setProImage] = useState<string | null>(null);

  // Edit State
  const [editPrompt, setEditPrompt] = useState('');
  const [editBaseImage, setEditBaseImage] = useState<string | null>(null);
  const [editedImage, setEditedImage] = useState<string | null>(null);
  const [editLoading, setEditLoading] = useState(false);
  const [isDragActive, setIsDragActive] = useState(false);

  // Camera State
  const [isCameraOpen, setIsCameraOpen] = useState(false);
  const [cameraStream, setCameraStream] = useState<MediaStream | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Clean up camera on unmount or mode switch
  useEffect(() => {
    return () => {
      if (cameraStream) {
        cameraStream.getTracks().forEach(track => track.stop());
      }
    };
  }, [cameraStream]);

  // --- Handlers ---

  const handleSurpriseMe = async () => {
    setPromptLoading(true);
    try {
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: { parts: [{ text: "Write a highly detailed, creative, and visually striking image generation prompt for an AI art generator. Keep it under 50 words. Do not include any intro text." }] }
        });
        if (response.text) {
            setGenPrompt(response.text.trim());
        }
    } catch (e) {
        console.error("Surprise me failed", e);
    } finally {
        setPromptLoading(false);
    }
  };

  const handleGen = async () => {
    if (!genPrompt) return;
    setGenLoading(true);
    setGeneratedImage(null);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

      if (genModel.startsWith('imagen')) {
         const hasKey = await ensureApiKeySelected();
         if (!hasKey) return;

         // Imagen Models use generateImages
         const response = await ai.models.generateImages({
             model: genModel,
             prompt: genPrompt,
             config: {
                 numberOfImages: 1,
                 outputMimeType: 'image/jpeg',
                 aspectRatio: aspectRatio as any, 
             }
         });
         
         const base64 = response.generatedImages?.[0]?.image?.imageBytes;
         if (base64) {
             setGeneratedImage(`data:image/jpeg;base64,${base64}`);
         } else {
             alert("No image generated by Imagen.");
         }

      } else {
        // Gemini Models use generateContent
        
        // For Gemini 3 Pro in standard tab, ensure key
        if (genModel === 'gemini-3-pro-image-preview') {
            const hasKey = await ensureApiKeySelected();
            if (!hasKey) return;
        }

        const config: any = {
            imageConfig: {
                aspectRatio: aspectRatio,
            }
        };

        // Image Size is only for Gemini 3 Pro
        if (genModel === 'gemini-3-pro-image-preview') {
            config.imageConfig.imageSize = imageSize;
        }

        const response = await ai.models.generateContent({
            model: genModel,
            contents: { parts: [{ text: genPrompt }] },
            config: config
        });

        // Extract image part using find to be safe
        const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
        if (part && part.inlineData) {
            setGeneratedImage(`data:image/png;base64,${part.inlineData.data}`);
        } else {
            alert("No image generated. Try a different prompt or model.");
        }
      }

    } catch (e: any) {
        console.error(e);
        if (e.message?.includes('403') || e.message?.includes('permission')) {
            alert("Permission Denied: Please ensure you have selected a paid API key project.");
        } else {
            alert("Generation failed. Please try again.");
        }
    } finally {
        setGenLoading(false);
    }
  };

  const handleProGen = async () => {
      if (!proPrompt) return;
      
      // Strict Key Check for Pro Model
      const hasKey = await ensureApiKeySelected();
      if (!hasKey) return;

      setProLoading(true);
      setProImage(null);

      try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
          const response = await ai.models.generateContent({
              model: 'gemini-3-pro-image-preview',
              contents: { parts: [{ text: proPrompt }] },
              config: {
                  imageConfig: {
                      aspectRatio: proAspectRatio,
                      imageSize: '2K' // Default to High Quality for Pro Tab
                  }
              }
          });

          const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
          if (part && part.inlineData) {
              setProImage(`data:image/png;base64,${part.inlineData.data}`);
          } else {
              alert("No image generated. Please try again.");
          }
      } catch (e: any) {
          console.error(e);
          if (e.message?.includes('403') || e.message?.includes('permission')) {
              alert("Permission Denied: Please select a paid API key project.");
          } else {
              alert("Pro generation failed.");
          }
      } finally {
          setProLoading(false);
      }
  };

  const handleEdit = async () => {
    if (!editPrompt || !editBaseImage) return;
    setEditLoading(true);
    setEditedImage(null);
    try {
       const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
       // Using Nano Banana (Gemini 2.5 Flash Image) for editing
       const response = await ai.models.generateContent({
           model: 'gemini-2.5-flash-image',
           contents: {
               parts: [
                   { inlineData: { mimeType: 'image/png', data: editBaseImage.split(',')[1] } },
                   { text: editPrompt }
               ]
           }
       });
       
       const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
       if (part && part.inlineData) {
         setEditedImage(`data:image/png;base64,${part.inlineData.data}`);
       } else {
           alert("Editing failed to produce an image. Ensure prompt is clear.");
       }
    } catch (e) {
        console.error(e);
        alert("Edit failed.");
    } finally {
        setEditLoading(false);
    }
  };

  const processFile = (file: File) => {
      if (file.type.startsWith('image/')) {
          const r = new FileReader();
          r.onload = () => setEditBaseImage(r.result as string);
          r.readAsDataURL(file);
      } else {
          alert("Please select a valid image file.");
      }
  };

  const onUploadEdit = (e: React.ChangeEvent<HTMLInputElement>) => {
      const f = e.target.files?.[0];
      if (f) processFile(f);
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setIsDragActive(true);
    } else if (e.type === "dragleave") {
      setIsDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  // Camera Handlers
  const startCamera = async () => {
    try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        setCameraStream(stream);
        setIsCameraOpen(true);
    } catch (e) {
        console.error("Camera error", e);
        alert("Could not access camera. Please check permissions.");
    }
  };

  const stopCamera = () => {
    if (cameraStream) {
        cameraStream.getTracks().forEach(track => track.stop());
        setCameraStream(null);
    }
    setIsCameraOpen(false);
  };

  const capturePhoto = () => {
    if (videoRef.current) {
        const canvas = document.createElement('canvas');
        canvas.width = videoRef.current.videoWidth;
        canvas.height = videoRef.current.videoHeight;
        const ctx = canvas.getContext('2d');
        if (ctx) {
            // Draw image to canvas
            ctx.drawImage(videoRef.current, 0, 0);
            setEditBaseImage(canvas.toDataURL('image/png'));
            stopCamera();
        }
    }
  };

  // Attach stream to video element
  useEffect(() => {
      if (isCameraOpen && cameraStream && videoRef.current) {
          videoRef.current.srcObject = cameraStream;
      }
  }, [isCameraOpen, cameraStream]);

  return (
    <div className="h-full w-full overflow-y-auto p-6 lg:p-10 pb-32">
      <div className="max-w-7xl mx-auto space-y-10 animate-fade-in">
        <header className="flex items-center gap-6 pb-6 border-b border-white/5">
            <div className="w-16 h-16 rounded-3xl bg-gradient-to-tr from-pink-500/20 to-rose-500/20 backdrop-blur-xl border border-white/10 flex items-center justify-center shadow-xl animate-scale-in">
                 <ImageIcon className="w-8 h-8 text-pink-200" />
            </div>
            <div>
                <h1 className="text-4xl font-semibold text-white tracking-tight">Image Studio</h1>
                <p className="text-white/40 mt-1 font-medium">Pro-Grade Generation & Editing</p>
            </div>
        </header>

         {/* Mode Switcher */}
         <div className="flex gap-2 p-1.5 bg-black/30 backdrop-blur-xl border border-white/5 rounded-2xl w-fit sticky top-0 z-20 shadow-lg">
            <button 
                onClick={() => setMode('generate')}
                className={`px-8 py-3 rounded-xl font-medium transition-all text-sm ${
                    mode === 'generate' 
                    ? 'bg-white/10 text-white shadow-lg border border-white/10 backdrop-blur-md' 
                    : 'text-white/40 hover:text-white hover:bg-white/5'
                }`}
            >
                Generate
            </button>
            <button 
                onClick={() => setMode('pro')}
                className={`px-8 py-3 rounded-xl font-medium transition-all text-sm flex items-center gap-2 ${
                    mode === 'pro' 
                    ? 'bg-gradient-to-r from-amber-500/20 to-orange-500/20 text-amber-200 border border-amber-500/30 shadow-lg backdrop-blur-md' 
                    : 'text-white/40 hover:text-white hover:bg-white/5'
                }`}
            >
                <Crown size={14} /> Pro
            </button>
            <button 
                onClick={() => setMode('edit')}
                className={`px-8 py-3 rounded-xl font-medium transition-all text-sm ${
                    mode === 'edit' 
                    ? 'bg-white/10 text-white shadow-lg border border-white/10 backdrop-blur-md' 
                    : 'text-white/40 hover:text-white hover:bg-white/5'
                }`}
            >
                Edit
            </button>
        </div>

        {/* --- Standard Create Mode --- */}
        {mode === 'generate' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 animate-slide-up">
                <div className="lg:col-span-1 space-y-6 glass-panel p-8 rounded-[2rem]">
                    <div className="space-y-3">
                        <div className="flex justify-between items-center">
                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Prompt</label>
                            <button 
                                onClick={handleSurpriseMe}
                                disabled={promptLoading}
                                className="text-[10px] flex items-center gap-1.5 text-pink-300 hover:text-white transition-all bg-pink-500/10 px-2 py-1 rounded-full border border-pink-500/20 active:scale-95"
                            >
                                {promptLoading ? <Loader2 size={10} className="animate-spin"/> : <Dice5 size={10}/>}
                                SURPRISE ME
                            </button>
                        </div>
                        <textarea 
                            value={genPrompt}
                            onChange={(e) => setGenPrompt(e.target.value)}
                            className="w-full h-40 glass-input rounded-2xl p-4 focus:ring-1 focus:ring-pink-500/50 outline-none resize-none text-white/90 leading-relaxed placeholder:text-white/20"
                            placeholder="A futuristic city made of crystal, cinematic lighting..."
                        />
                    </div>

                    <div className="space-y-5">
                        <div className="space-y-2">
                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Model</label>
                            <div className="relative">
                                <Palette className="absolute left-4 top-3.5 text-white/40" size={16} />
                                <select 
                                    value={genModel}
                                    onChange={(e) => setGenModel(e.target.value)}
                                    className="w-full glass-input rounded-xl p-3 pl-12 outline-none appearance-none cursor-pointer text-sm text-white/80"
                                >
                                    <option value="gemini-2.5-flash-image">Gemini 2.5 Flash (Fast)</option>
                                    <option value="gemini-3-pro-image-preview">Gemini 3 Pro (High Quality)</option>
                                    <option value="imagen-4.0-generate-001">Imagen 4 (Creative)</option>
                                </select>
                            </div>
                        </div>

                        <div className="space-y-2">
                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Aspect Ratio</label>
                            <select 
                                value={aspectRatio}
                                onChange={(e) => setAspectRatio(e.target.value as AspectRatio)}
                                className="w-full glass-input rounded-xl p-3 outline-none cursor-pointer text-sm text-white/80"
                            >
                                {['1:1', '3:4', '4:3', '9:16', '16:9'].map(r => (
                                    <option key={r} value={r}>{r}</option>
                                ))}
                            </select>
                        </div>
                        
                        {/* Quality only available for Gemini 3 Pro */}
                        {genModel === 'gemini-3-pro-image-preview' && (
                            <div className="space-y-2">
                                <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Quality</label>
                                <div className="flex bg-white/5 rounded-xl p-1 border border-white/5">
                                    {['1K', '2K', '4K'].map(s => (
                                        <button
                                            key={s}
                                            onClick={() => setImageSize(s as ImageSize)}
                                            className={`flex-1 py-1.5 rounded-lg text-xs font-medium transition-all ${
                                                imageSize === s 
                                                ? 'bg-white text-black shadow-sm' 
                                                : 'text-white/40 hover:text-white'
                                            }`}
                                        >
                                            {s}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>

                    <button 
                        onClick={handleGen}
                        disabled={genLoading || !genPrompt}
                        className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg active:scale-95 ${
                            genLoading || !genPrompt 
                            ? 'bg-white/5 text-white/20 cursor-not-allowed' 
                            : 'bg-white text-black hover:bg-white/90 hover:scale-[1.02]'
                        }`}
                    >
                         {genLoading ? <Loader2 className="animate-spin" /> : <ImagePlus size={18} />}
                         Generate
                    </button>
                </div>

                <div className="lg:col-span-2 glass-panel rounded-[2rem] flex items-center justify-center min-h-[600px] relative overflow-hidden bg-black/40 border border-white/10">
                    {generatedImage ? (
                        <div className="relative group w-full h-full flex items-center justify-center p-8 animate-scale-in">
                            <img src={generatedImage} alt="Generated" className="max-w-full max-h-[700px] object-contain shadow-2xl rounded-lg" />
                             <a href={generatedImage} download={`generated-${genModel}.png`} className="absolute bottom-8 right-8 p-4 bg-white/10 backdrop-blur-md hover:bg-white/20 text-white rounded-full shadow-lg border border-white/10 transition-transform hover:scale-110 active:scale-90">
                                <Download size={24} />
                            </a>
                        </div>
                    ) : (
                        <div className="text-white/20 flex flex-col items-center animate-pulse">
                            <Sparkles className="w-24 h-24 mb-6 opacity-10" />
                            <p className="font-medium tracking-wide">Your masterpiece awaits</p>
                        </div>
                    )}
                </div>
            </div>
        )}

        {/* --- Pro Mode --- */}
        {mode === 'pro' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 animate-slide-up">
                <div className="lg:col-span-1 space-y-6 glass-panel p-8 rounded-[2rem] border-amber-500/20 shadow-[0_0_50px_-20px_rgba(245,158,11,0.2)]">
                    <div className="flex items-center gap-2 text-amber-300 mb-2">
                        <Crown size={20} />
                        <h3 className="font-bold text-lg tracking-tight">Gemini 3 Pro</h3>
                    </div>
                    
                    <div className="space-y-3">
                        <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Detailed Prompt</label>
                        <textarea 
                            value={proPrompt}
                            onChange={(e) => setProPrompt(e.target.value)}
                            className="w-full h-48 glass-input rounded-2xl p-5 focus:ring-1 focus:ring-amber-500/50 outline-none resize-none text-white/90 leading-relaxed placeholder:text-white/20 text-base"
                            placeholder="Describe your vision in extreme detail..."
                        />
                    </div>

                    <div className="space-y-4">
                        <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Ratio</label>
                        <div className="grid grid-cols-3 gap-3">
                            <button
                                onClick={() => setProAspectRatio('1:1')}
                                className={`flex flex-col items-center justify-center gap-2 p-3 rounded-xl border transition-all ${
                                    proAspectRatio === '1:1' 
                                    ? 'bg-amber-500/20 border-amber-500/50 text-amber-200' 
                                    : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10'
                                }`}
                            >
                                <Square size={20} />
                                <span className="text-[10px] font-medium">Square</span>
                            </button>
                            <button
                                onClick={() => setProAspectRatio('16:9')}
                                className={`flex flex-col items-center justify-center gap-2 p-3 rounded-xl border transition-all ${
                                    proAspectRatio === '16:9' 
                                    ? 'bg-amber-500/20 border-amber-500/50 text-amber-200' 
                                    : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10'
                                }`}
                            >
                                <Monitor size={20} />
                                <span className="text-[10px] font-medium">Wide</span>
                            </button>
                            <button
                                onClick={() => setProAspectRatio('9:16')}
                                className={`flex flex-col items-center justify-center gap-2 p-3 rounded-xl border transition-all ${
                                    proAspectRatio === '9:16' 
                                    ? 'bg-amber-500/20 border-amber-500/50 text-amber-200' 
                                    : 'bg-white/5 border-white/5 text-white/40 hover:bg-white/10'
                                }`}
                            >
                                <Smartphone size={20} />
                                <span className="text-[10px] font-medium">Story</span>
                            </button>
                        </div>
                    </div>

                    <div className="pt-4">
                        <button 
                            onClick={handleProGen}
                            disabled={proLoading || !proPrompt}
                            className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg active:scale-95 ${
                                proLoading || !proPrompt
                                ? 'bg-white/5 text-white/20 cursor-not-allowed' 
                                : 'bg-gradient-to-r from-amber-500 to-orange-600 text-white hover:opacity-90 hover:scale-[1.02] shadow-amber-900/20'
                            }`}
                        >
                            {proLoading ? <Loader2 className="animate-spin" /> : <Sparkles size={18} />}
                            Generate Pro Image
                        </button>
                        <p className="text-center text-[10px] text-white/30 mt-3 font-medium">
                            Requires API Key selection. Generates 2K resolution.
                        </p>
                    </div>
                </div>

                <div className="lg:col-span-2 glass-panel rounded-[2rem] flex items-center justify-center min-h-[600px] relative overflow-hidden bg-black/40 border border-white/10">
                    {proImage ? (
                        <div className="relative group w-full h-full flex items-center justify-center p-8 animate-scale-in">
                            <img src={proImage} alt="Pro Generated" className="max-w-full max-h-[700px] object-contain shadow-2xl rounded-lg" />
                             <a href={proImage} download={`pro-gemini-3-${Date.now()}.png`} className="absolute bottom-8 right-8 p-4 bg-amber-500/20 backdrop-blur-md hover:bg-amber-500/40 text-amber-100 rounded-full shadow-lg border border-amber-500/30 transition-transform hover:scale-110 active:scale-90">
                                <Download size={24} />
                            </a>
                        </div>
                    ) : (
                        <div className="text-white/20 flex flex-col items-center animate-pulse">
                            <Crown className="w-24 h-24 mb-6 opacity-10 text-amber-200" />
                            <p className="font-medium tracking-wide">Pro Studio Ready</p>
                        </div>
                    )}
                </div>
            </div>
        )}

        {/* --- Edit Mode --- */}
        {mode === 'edit' && (
             <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-slide-up">
                 <div className="space-y-6 glass-panel p-8 rounded-[2rem]">
                    <div className="space-y-3">
                        <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Base Image</label>
                        
                        {isCameraOpen ? (
                            <div className="relative w-full h-72 bg-black rounded-2xl overflow-hidden border border-white/10 ring-1 ring-white/20 shadow-2xl animate-scale-in">
                                <video 
                                    ref={videoRef} 
                                    autoPlay 
                                    playsInline 
                                    muted
                                    className="w-full h-full object-cover transform scale-x-[-1]" 
                                />
                                <div className="absolute top-4 right-4 z-20">
                                    <button 
                                        onClick={stopCamera} 
                                        className="bg-black/50 text-white p-2 rounded-full hover:bg-black/70 backdrop-blur-md active:scale-95"
                                    >
                                        <X size={16} />
                                    </button>
                                </div>
                                <div className="absolute bottom-6 left-0 right-0 flex justify-center gap-4 z-10">
                                    <button 
                                        onClick={capturePhoto} 
                                        className="w-16 h-16 bg-white rounded-full shadow-lg hover:scale-110 transition-transform border-4 border-gray-200/50 active:scale-95"
                                    />
                                </div>
                            </div>
                        ) : (
                            <div className="flex flex-col gap-4">
                                <div 
                                    onDragEnter={handleDrag}
                                    onDragLeave={handleDrag}
                                    onDragOver={handleDrag}
                                    onDrop={handleDrop}
                                    className={`w-full h-72 border border-dashed rounded-2xl transition-all overflow-hidden relative flex flex-col items-center justify-center bg-white/5 ${
                                        isDragActive 
                                        ? 'border-pink-500 bg-pink-500/10 scale-[1.02]' 
                                        : 'border-white/20 hover:border-white/40 hover:bg-white/10'
                                    }`}
                                >
                                    {editBaseImage ? (
                                        <div className="relative w-full h-full group animate-scale-in">
                                            <img src={editBaseImage} className="absolute inset-0 w-full h-full object-contain p-4" />
                                            <button 
                                                onClick={() => setEditBaseImage(null)}
                                                className="absolute top-4 right-4 p-2 bg-black/60 text-white rounded-full hover:bg-red-500 transition-colors opacity-0 group-hover:opacity-100 active:scale-90"
                                            >
                                                <Trash2 size={16} />
                                            </button>
                                        </div>
                                    ) : (
                                        <div className="flex flex-col items-center gap-6 z-10 w-full pointer-events-none">
                                            <div className="flex flex-col items-center text-white/40">
                                                <Upload className="w-10 h-10 mb-3 opacity-50" />
                                                <span className="text-sm font-medium">Drag & Drop Image</span>
                                            </div>

                                            <div className="flex gap-3 pointer-events-auto">
                                                <label className="cursor-pointer bg-white/10 hover:bg-white/20 text-white px-5 py-2.5 rounded-xl border border-white/10 transition-all text-sm font-medium hover:scale-105 active:scale-95">
                                                    Files
                                                    <input type="file" className="hidden" accept="image/*" onChange={onUploadEdit} />
                                                </label>
                                                <button 
                                                    onClick={startCamera}
                                                    className="flex items-center gap-2 px-5 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl border border-white/10 transition-all text-sm font-medium hover:scale-105 active:scale-95"
                                                >
                                                    <Camera size={16} /> Camera
                                                </button>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                    
                    <div className="space-y-3">
                        <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Edit Instruction</label>
                        <input 
                            type="text"
                            value={editPrompt}
                            onChange={(e) => setEditPrompt(e.target.value)}
                            placeholder="e.g., 'Make it cyberpunk style' or 'Remove the background'"
                            className="w-full glass-input rounded-xl p-4 outline-none focus:ring-1 focus:ring-pink-500/50 text-white placeholder-white/20"
                        />
                    </div>

                    <button 
                        onClick={handleEdit}
                        disabled={editLoading || !editPrompt || !editBaseImage}
                        className={`w-full py-4 rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg active:scale-95 transition-all ${
                            editLoading || !editPrompt || !editBaseImage
                            ? 'bg-white/5 text-white/20' 
                            : 'bg-white text-black hover:bg-white/90 hover:scale-[1.02]'
                        }`}
                    >
                         {editLoading ? <Loader2 className="animate-spin" /> : <Wand size={18} />}
                         Apply Edit
                    </button>
                 </div>

                 <div className="glass-panel rounded-[2rem] flex items-center justify-center min-h-[500px] border border-white/10 bg-black/40">
                     {editedImage ? (
                         <div className="relative group w-full h-full flex items-center justify-center p-8 animate-scale-in">
                            <img src={editedImage} alt="Edited" className="max-w-full max-h-[600px] object-contain shadow-2xl rounded-lg" />
                            <a href={editedImage} download="edited-image.png" className="absolute bottom-8 right-8 p-4 bg-white/10 backdrop-blur-md hover:bg-white/20 text-white rounded-full shadow-lg border border-white/10 transition-transform hover:scale-110 active:scale-90">
                                <Download size={24} />
                            </a>
                         </div>
                     ) : (
                         <div className="text-white/20 text-center">
                             <Wand className="w-20 h-20 mx-auto mb-4 opacity-10" />
                             <p className="font-medium tracking-wide">Result Preview</p>
                         </div>
                     )}
                 </div>
             </div>
        )}
      </div>
    </div>
  );
};
